# Generated by Django 4.2.9 on 2026-01-05 00:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('education', models.CharField(choices=[('High School or Below', 'High School or Below'), ('College', 'College'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctor', 'Doctor')], max_length=50)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=1)),
                ('salary', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('Star', 'Star'), ('Nova', 'Nova'), ('Aurora', 'Aurora')], max_length=20)),
                ('enrollment_type', models.CharField(choices=[('Standard', 'Standard'), ('2018 Promotion', '2018 Promotion')], max_length=50)),
                ('enrollment_date', models.DateField()),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('total_flights', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0.0)),
                ('flight_class', models.CharField(choices=[('Eco', 'Economy'), ('Eco Plus', 'Economy Plus'), ('Business', 'Business')], max_length=20)),
                ('travel_type', models.CharField(choices=[('Personal Travel', 'Personal Travel'), ('Business travel', 'Business Travel')], max_length=20)),
                ('points_accumulated', models.FloatField(default=0.0)),
                ('points_redeemed', models.FloatField(default=0.0)),
                ('dollar_cost_points_redeemed', models.FloatField(default=0.0)),
                ('satisfaction', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_value', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentation_cluster', models.IntegerField(blank=True, null=True)),
                ('segmentation_label', models.CharField(blank=True, max_length=50)),
                ('clv_prediction', models.FloatField(blank=True, null=True)),
                ('churn_classification', models.IntegerField(blank=True, null=True)),
                ('churn_risk_label', models.CharField(blank=True, max_length=50)),
                ('churn_months', models.FloatField(blank=True, null=True)),
                ('highly_engaged', models.IntegerField(blank=True, null=True)),
                ('engagement_label', models.CharField(blank=True, max_length=50)),
                ('equity_segment_cluster', models.IntegerField(blank=True, null=True)),
                ('equity_segment_label', models.CharField(blank=True, max_length=100)),
                ('loyalty_points_classification', models.IntegerField(blank=True, null=True)),
                ('loyalty_cluster', models.IntegerField(blank=True, null=True)),
                ('loyalty_cluster_label', models.CharField(blank=True, max_length=100)),
                ('points_forecast', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], default='Low', max_length=20)),
                ('potential_category', models.CharField(choices=[('Low', 'Low Potential'), ('Medium', 'Medium Potential'), ('High', 'High Potential')], default='Medium', max_length=20)),
                ('predictions_completed', models.BooleanField(default=False)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raw_predictions', models.JSONField(blank=True, default=dict)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='airline_project.client')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
            },
        ),
    ]
