# Generated by Django 6.0 on 2026-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlprediction',
            name='khalil_cluster_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='khalil_cluster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='khalil_cluster_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='khalil_preferred_season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='khalil_similar_neighbors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
