# Generated by Django 6.0 on 2026-01-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_project', '0002_mlprediction_khalil_cluster_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlprediction',
            name='tier_progression_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='tier_progression_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='tier_upgrade_prediction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='tier_upgrade_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
